#mkdocs.yml

# -------------------------------------------------------------
# CONFIGURACIÓN GENERAL DEL SITIO
# -------------------------------------------------------------
site_name: Tarea 0

# -------------------------------------------------------------
# ESTRUCTURA DE NAVEGACIÓN (MENÚ)
# -------------------------------------------------------------
nav:
  - Tarea 0: index.md
  - Git: git.md
  - Git Actions: gitActions.md
  - Docker: docker.md
  - Conclusiones: conclusiones.md

# -------------------------------------------------------------
# DIRECTORIOS
# -------------------------------------------------------------
doc_dir: docs 
doc_dir: images
# -------------------------------------------------------------
# TEMA
# -------------------------------------------------------------
theme:
    name: simple-blog